sudo: false
language: scala
jdk: oraclejdk8
script:
  - sbt compile
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bd430cb22907daf53306
    on_success: change
    on_failure: always
    on_start: never
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
